# Generated by Django 5.2.1 on 2025-05-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Book title", max_length=200)),
                ("author", models.CharField(help_text="Author name", max_length=100)),
                ("genre", models.CharField(help_text="Book genre", max_length=50)),
                ("description", models.TextField(help_text="Book description/blurb")),
                (
                    "published_year",
                    models.IntegerField(help_text="Year of publication"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_year", "title"],
            },
        ),
    ]
